name: full test for the all supported Python versions

on:
  push:
    branches:
      - master
    paths:
      - "covsirphy/__version__.py"
      - "pyproject.toml"

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # CovsirPhy with Python 3.7 and 3.8 will be tested with Semaphore CI
        python-version: [3.6.9, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # pip install
    - name: pip install and test
      run: |
        pip install pip --upgrade
        pip install .
        pip install pytest
        pytest -v --maxfail=1 tests
