on: 
  issue_comment:
    types: [created]
name: Automatic Rebase by 'rebase' comment (not '/rebase')
# https://github.com/marketplace/actions/automatic-rebase
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, 'rebase')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  